### PR TITLE
[WIP] C++ backend

### PR DESCRIPTION
**Pull request by cmnrd**
This is a C++ backend for lingua franka. While there are still some open issues, the backend is pretty complete and covers most aspects of the language. I adapted most of the C test programms to show that the new C++ works.

The C++ backend is a pure code generator and does not provide a runtime library by itself. It relies
instead on [enactor](https://github.com/tud-ccc/enactor), a standalone framework for the creation of reactor networks in C++. This dependency is automatically pulled in when building the target.

Please have alook at this and let me know what you think.

These are some of the more important open issues:
- Support for preambles is somewhat limited. The C++ backend generates a source and a header file for each reactor and currently the preamble goes into the header. This works well with includes, but causese problems, e.g., with function definitions as those should be placed in a source file.
- While local deadlines (on reactions) are supported by this backend, deadlines on input ports are not supported. I am somewhat confused by the deadline's ability to schedule another action at the same logical time. This needs dome clarification.
- While there are test programs, they are not yet integrated with the test system of LF.

### CODE REVIEW

**Comment by edwardalee** [comment]
Cool!  I will take a close look soon...

We have removed hierarchical deadlines from the language specification because we discovered a number of problems with them, so it’s a good thing you didn’t implement them.

Edward

**Comment by lhstrh** [comment]
I merged this into main and made some adjustments to accommodate recent
changes to the grammar. The next action item would be to fix continuous
integration of the cpp tests. I'll send you an update when this is done.

Marten

--
Marten Lohstroh, MSc. | Ph.D. Candidate
University of California | 545Q Cory Hall
Berkeley, CA 94720  | +1 510 282 9135

**Comment by lhstrh** [comment]
I renamed `C/testFile.text` to `test-manifest` (moved it up one directory).
The idea is that all targets should implement these tests; if they are not
present, a warning is thrown by run-lf-tests. I expect the next Travis
build to error out because some of the recent changes to CppGenerator are
causing compile errors. To run the Cpp tests only, run: `run-lf-tests Cpp`

Marten

--
Marten Lohstroh, MSc. | Ph.D. Candidate
University of California | 545Q Cory Hall
Berkeley, CA 94720  | +1 510 282 9135

**Comment by edwardalee** [comment]
I am unable to get this to work using either the command-line compiler or the Eclipse IDE (with different errors for each).
I’ve pushed a small change that prints out the actual cmake command that gets executed so we can see what’s going on.
I also pushed a small to use .toString rather than .toFileString because the latter always returns null and causes a null-pointer exception (at least in the Eclipse IDE).

The command-line compiler yields (in the tests/Cpp directory):

> lfc AsyncCallback.lf
…
--- Running: cmake -DCMAKE_INSTALL_PREFIX=/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp -DENACTOR_BUILD_DIR=/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/enactor /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/AsyncCallback
CMake Error at CMakeLists.txt:48 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "AsyncCallback".


-- Configuring incomplete, errors occurred!
See also "/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/AsyncCallback/CMakeFiles/CMakeOutput.log".
ERRROR (while executing cmake)
Code generation finished.



Running the cmake command by hand in the same directory yields the same error.

I’m not sure what is going on. Suggestions?



For the Eclipse IDE, a different error occurs.  I set up project using the instructions here (replacing C with Cpp):

https://github.com/icyphy/lingua-franca/wiki/Downloading-and-Building#5-running-and-editing-the-c-target-tests-in-eclipse

After fixing the null-pointer exception due to toFileString, I get a bogus cmake command, as shown on this console output:

--- Running: cmake -DCMAKE_INSTALL_PREFIX=/Users/eal/eclipse/java-2018-12/Eclipse.app/Contents/MacOS -DENACTOR_BUILD_DIR=/Users/eal/eclipse/java-2018-12/Eclipse.app/Contents/MacOS/build/enactor /Users/eal/eclipse/java-2018-12/Eclipse.app/Contents/MacOS/src-gen/AsyncCallback
1510 [Worker-3: Building workspace] ERROR org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/CppTests/AsyncCallback.lf'.
java.io.IOException: Cannot run program "cmake" (in directory "/Users/eal/eclipse/java-2018-12/Eclipse.app/Contents/MacOS/build/AsyncCallback"): error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.icyphy.generator.CppGenerator.doCompile(CppGenerator.java:1846)
	at org.icyphy.generator.CppGenerator.doGenerate(CppGenerator.java:139)
…


Note that the directories being specified are completely wrong. I think this is because the code generator is relying on using ‘pwd’, which it should not…

Edward


———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Pull request merged**
